export { default as Login } from './login/Login';
export { default as Register } from './register/Register';
export { default as Profile } from './profile/Profile';
export { default as Home } from './home/Home'
export { default as Players } from './players/Players';
export { default as Rankings } from './rankings/Rankings';
export { default as TournamentCalendar } from './tournament-calendar/TournamentCalendar';
export { default as TournamentSubmission } from './tournament-submission/TournamentSubmission';
export { default as MyTournaments } from './my-tournaments/MyTournaments';
export { default as Chats } from './chats/Chats';
export { default as About } from './about/About';
